# Generated by Django 4.0.4 on 2022-04-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('payment_method', models.CharField(choices=[('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('cash', 'Cash')], max_length=11)),
                ('card_number', models.CharField(blank=True, max_length=12, null=True)),
                ('payment_import', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
